export const LOGIN_SUCCESS = 'LOGIN'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'
export const SHOW_LOGIN_FORM = 'SHOW_LOGIN_FORM'
export const INPUT_LOGIN = 'INPUT_LOGIN'
export const INPUT_PASSWORD = 'INPUT_PASSWORD'
